name: CI-CD

on:
  push:
    branches: ["main"]


jobs:
    Run-tests:
        runs-on: [self-hosted, linux]
        steps:
            -   name: checkout source code
                uses: actions/checkout@v3
            -
                name: Install python dependencies
                run: pip install -r requirements.txt
              
            -
                name: Run Unit tests
                run: python ./tests/test.py
    docker-build:
        runs-on: [self-hosted, linux]
        needs: ['Run-tests']       
        steps:
            -   
                name: checkout source code.
                uses: actions/checkout@v3 
            -
                name: Build docker image
                run:  sh ./scripts/dockerBuild.sh
    Deployment:
        runs-on: [self-hosted, linux]
        needs: ['Run-tests','docker-build']     
        steps:  
            -
                name: deploy image
                run:  sh ./scripts/deploy.sh

                  
